import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>LDK Al-Ukhuwah UNISMA BEKASI</title>
        <meta
          name="description"
          content="Generated by LDK Al-Ukhuwah UNISMA BEKASI"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
